# Generated by Django 5.1.1 on 2024-11-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, default='https://example.com/default-image.jpg'),
        ),
    ]
