# Generated by Django 5.1.1 on 2024-10-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='download_link',
            field=models.URLField(default='http://example.com '),
            preserve_default=False,
        ),
    ]
