# Generated by Django 5.1.1 on 2024-10-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_download_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
    ]
