# Generated by Django 5.1.1 on 2024-11-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='credits',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='view_count',
        ),
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
