# Generated by Django 5.1.2 on 2024-11-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review'),
        ('app', '0004_review'),
    ]

    operations = [
    ]
