# Generated by Django 5.1.1 on 2024-12-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='download_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-fiction'), ('fantasy', 'Fantasy'), ('science', 'Science'), ('history', 'History'), ('other', 'Other')], default='fiction', max_length=50),
        ),
    ]
