# Generated by Django 5.1.2 on 2024-12-13 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bookcreation_genre_remove_book_slug'),
        ('app', '0006_genre_book_genres'),
    ]

    operations = [
    ]
