# Generated by Django 5.1.1 on 2024-11-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_genre_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
